version: "3"
services:
  postgres-service:
    image: postgres:13.3
    restart: always
    env_file:
      - ./project/.env
    container_name: "ravon-postgres"
    environment:
      - POSTGRES_DB=ravon
      - POSTGRES_USER=ravon
      - POSTGRES_PASSWORD=ravon
    ports:
      - 5433
#    volumes:
#      - ravon-db:/var/lib/postgresql/data:rw
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
