#!/usr/bin/env bash

if ! hash python3; then
    echo "python3 is not installed"
    exit 1
fi

ver=$(python3 -V 2>&1 | sed 's/.* \([0-9]\).\([0-9]\).*/\1\2/')
if [ "$ver" -lt "38" ]; then
    echo "This script requires python 3.8 or greater"
    exit 1
fi


function activate_development_environment() {
    echo "Testing virtual environment path"

    devlopment_environment_path="${PWD}/.env/bin/activate"
    if [ ! -e "$devlopment_environment_path" ]; then
        echo "Virtual environment not found!"
        echo "Creating new virual environment"
        python3 -m venv --prompt="v" .env
    fi
    source $devlopment_environment_path
    source "${PWD}/project/.env"
    pip install -r requirements/base.txt
}

function deactivate_development_environment() {
    echo "Testing virtual environment"
    echo $VIRTUAL_ENV
    deactivate
    rm -rf .env
}



case $1 in
  activate)
    echo "===================================================================="
    echo "- Starting activation"
    echo "===================================================================="
    activate_development_environment
  	;;
  deactivate)
    echo "===================================================================="
    echo "- Starting deactivation"
    echo "===================================================================="
    deactivate_development_environment
  	;;
  startdb)
    echo "===================================================================="
  	echo "- Starting database"
    echo "===================================================================="
    docker-compose -f ${PWD}/docker-compose.yml up -d
    echo "===================================================================="
  	echo "- Waiting  database"
    echo "===================================================================="
    sleep 3
    python manage.py migrate
  	;;
  stopdb)
    echo "===================================================================="
  	echo "- Stopping database"
    echo "===================================================================="
    docker-compose -f ${PWD}/docker-compose.yml stop
  	;;
  dropdb)
    echo "===================================================================="
  	echo "- Dropping database"
    echo "===================================================================="
    docker-compose -f ${PWD}/docker-compose.yml down -v
  	;;
  image_build)
    echo "===================================================================="
  	echo "- Building Image"
    echo "===================================================================="
    docker build -t ${DOCKER_IMAGE}  -f Dockerfile .
  	;;
  image_push)
    echo "===================================================================="
  	echo "- Building Image"
    echo "===================================================================="
    docker build -t ${DOCKER_IMAGE} -f /Dockerfile .
    docker tag ${DOCKER_IMAGE}:latest ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
    echo "===================================================================="
  	echo "- AWS Login"
    echo "===================================================================="
    aws ecr get-login-password --profile ${DOCKER_PROFILE} |  docker login --username AWS --password-stdin ${DOCKER_REGISTRY}

    echo "===================================================================="
  	echo "- Push Image"
    echo "===================================================================="
    docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:latest
    ;;



  *)
  	echo "Sorry, I don't understand"
  	;;
esac
