# Generated by Django 3.1.3 on 2021-09-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registration_phone_model',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='registration_phone_type',
        ),
        migrations.CreateModel(
            name='DriverPhoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=100, null=True)),
                ('phone_model', models.CharField(max_length=100, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
