# Generated by Django 3.1.3 on 2021-09-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_account', '0006_currentlocationofdriver_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlocationofdriver',
            name='radius',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentlocationofdriver',
            name='driver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
