# Generated by Django 3.1.3 on 2021-09-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('latitude', models.TextField()),
                ('longtitude', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MinimumPriceForKm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine', models.IntegerField(choices=[(1, 'Morning Routine'), (2, 'Noon Routine'), (3, 'Noon Routine'), (4, 'Evening Routine')])),
                ('start_range', models.TimeField(unique=True)),
                ('end_range', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='from_point',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='reason_to_cancel',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='to_point',
        ),
        migrations.RemoveField(
            model_name='trippath',
            name='trip',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.FloatField(default=1),
        ),
        migrations.DeleteModel(
            name='RateOfDriver',
        ),
        migrations.DeleteModel(
            name='ReasonToCancelTrip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripPath',
        ),
        migrations.AddField(
            model_name='minimumpriceforkm',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.routine'),
        ),
        migrations.AlterUniqueTogether(
            name='minimumpriceforkm',
            unique_together={('city', 'routine')},
        ),
    ]
