# Generated by Django 3.1.3 on 2021-09-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type_of_car',
            field=models.CharField(choices=[('standard', 'Standard'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=100, null=True),
        ),
    ]
