# Generated by Django 3.1.3 on 2021-09-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_car_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='number',
            new_name='gos_number',
        ),
        migrations.AddField(
            model_name='car',
            name='manifacture_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account_account.customuser'),
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_front_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_left_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_back_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_right_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_front_interior_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_rear_interior_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('car_open_truck_image', models.FileField(blank=True, null=True, upload_to='plan_request/')),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='created', max_length=60)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicensePhotoCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.FileField(blank=True, null=True, upload_to='')),
                ('back_image', models.FileField(blank=True, null=True, upload_to='')),
                ('licence_and_driver', models.FileField(blank=True, null=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarTechPassportCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.FileField(blank=True, null=True, upload_to='')),
                ('back_image', models.FileField(blank=True, null=True, upload_to='')),
                ('tech_passport_and_driver', models.FileField(blank=True, null=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.carcolor'),
        ),
    ]
